"""
main.py – Entry-point for the Agentic RML Pipeline.

Usage:
    # Normal run (no evaluation)
    python main.py

    # Run + Level 1 evaluation only
    python main.py --eval 1

    # Run + all 3 evaluation levels
    python main.py --eval 1 2 3

    # Run + Level 1 and 3 (skip gold comparison)
    python main.py --eval 1 3

    # Specify a custom gold KG path for Level 2
    python main.py --eval 1 2 3 --gold data/gold/bikeshare_gold.nt

    # Run with Competency Questions (inline)
    python main.py --cqs "Can I identify the publisher of the parent document?" "Who authored it?"

    # Run with Competency Questions (from file, one per line)
    python main.py --cqs @cqs.txt
"""

import argparse
import os
import re
import sys
import warnings
import time
import uuid
from datetime import datetime

from dotenv import load_dotenv

load_dotenv()

# Silence noisy deprecation warnings from third-party libraries
warnings.filterwarnings("ignore", category=FutureWarning, module="morph_kgc")
warnings.filterwarnings("ignore", category=FutureWarning, module="pandas")
try:
    import pandas as _pd
    _pd.set_option('future.no_silent_downcasting', True)
except Exception:
    pass

# Suppress duplicate/verbose logging from morph_kgc and yatter
import logging as _logging
_logging.getLogger("morph_kgc").setLevel(_logging.WARNING)
_logging.getLogger("yatter").setLevel(_logging.WARNING)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Agentic RML Pipeline with optional multi-level evaluation.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--eval", nargs="*", type=int, default=None, dest="eval_levels",
        help="Evaluation levels to run after the pipeline. "
             "Any combination of 1, 2, 3.  Omit to skip evaluation.",
    )
    parser.add_argument(
        "--gold", type=str, default=None,
        help="Path to the gold-standard KG (N-Triples) for Level 2 evaluation.",
    )
    parser.add_argument(
        "--dashboard", "-d", nargs="?", type=int, const=5, default=None,
        metavar="N",
        help="Launch the metrics dashboard after the run. "
             "Optionally pass the number of latest runs to compare (default: 5). "
             "Example: --dashboard 3",
    )
    parser.add_argument(
        "--cqs", nargs="*", type=str, default=None,
        help="Competency Questions for CQ validation. "
             "Pass as quoted strings: --cqs 'Can I identify the publisher?' 'Who authored it?' "
             "Or pass a file path: --cqs @cqs.txt (one question per line). "
             "If omitted, CQs are auto-generated from the schema and ontology.",
    )
    parser.add_argument(
        "--base-uri", type=str, default=None, dest="base_uri",
        help="Base URI for all subject (entity) URIs in the generated KG. "
             "E.g. --base-uri http://mykg.org/  "
             "Overrides the BASE_URI environment variable. "
             "When set, all subject templates like dbo:Film/$(id) are rewritten "
             "to use this namespace: mykg:Film/$(id).",
    )
    parser.add_argument(
        "--sparql", nargs="*", type=str, default=None,
        help="Direct SPARQL ASK queries to validate against the generated KG. "
             "Executed as-is — no LLM translation. "
             "Pass as quoted strings: --sparql 'ASK { ?s a ex:Class }' "
             "Or pass a file path: --sparql @queries.rq (one query per line, separated by blank lines).",
    )
    parser.add_argument(
        "--shacl", action="store_true", default=False,
        help="Enable SHACL validation of the generated KG against ontology-derived "
             "shapes auto-generated by Astrea.  Dataset-agnostic: shapes are derived "
             "from whatever ontology the pipeline is using.",
    )
    return parser.parse_args()


def main():
    args = parse_args()

    from graph.workflow import build_rml_graph

    app = build_rml_graph()

    # Create a unique timestamped directory for this specific run
    current_run_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_directory = f"data/output/run_{current_run_timestamp}"
    os.makedirs(run_directory, exist_ok=True)

    # ── Parse Competency Questions ───────────────────────────────
    competency_questions = []
    if args.cqs:
        for item in args.cqs:
            # Support both @file.txt and bare file.txt for file loading
            file_path = item[1:] if item.startswith("@") else item
            if os.path.isfile(file_path):
                # Load from file: one question per line
                with open(file_path) as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#"):
                            competency_questions.append(line)
            else:
                competency_questions.append(item)

    if competency_questions:
        print(f"  Loaded {len(competency_questions)} Competency Question(s)")
        for i, q in enumerate(competency_questions, 1):
            print(f"    CQ{i}: {q}")
    else:
        print("  No CQs provided — will auto-generate from schema + ontology.")

    # ── Parse direct SPARQL queries ──────────────────────────────
    user_sparql_queries = []
    if args.sparql:
        for item in args.sparql:
            file_path = item[1:] if item.startswith("@") else item
            if os.path.isfile(file_path):
                # Load from file: queries separated by blank lines
                with open(file_path) as f:
                    raw = f.read()
                for block in re.split(r'\n\s*\n', raw):
                    block = block.strip()
                    if block and block.upper().startswith("ASK"):
                        user_sparql_queries.append(block)
            else:
                user_sparql_queries.append(item)

    if user_sparql_queries:
        print(f"  Loaded {len(user_sparql_queries)} direct SPARQL query(ies)")

    # ── Normalise base URI ───────────────────────────────────────
    raw_base_uri = args.base_uri or os.getenv("BASE_URI", "http://example.org/")
    # If user passed a bare domain (e.g. mykg.org), add the http:// scheme
    if raw_base_uri and not raw_base_uri.startswith(("http://", "https://", "urn:")):
        raw_base_uri = "http://" + raw_base_uri
        print(f"  [INFO] Base URI normalised to: {raw_base_uri}")

    initial_state = {
        "csv_path": os.getenv("INPUT_CSV_PATH"),
        "ontology_path": os.getenv("INPUT_ONTOLOGY_PATH"),
        "base_uri": raw_base_uri,
        "competency_questions": competency_questions,
        "generated_cqs": [],
        "user_sparql_queries": user_sparql_queries,
        "schema_info": {},
        "ontology_info": {},
        "mapping_plan": {},
        "schema_alignment": {},
        "prefixes_output": "",
        "entity_yarrrml": "",
        "yarrrml_output": "",
        "rdf_output": "",
        "sparql_validation_results": [],
        "feedback": "",
        "retry_count": 0,
        "cq_sparql_retry_count": 0,
        "messages": [],
        "run_dir": run_directory,
        "predicate_conflict_cols": [],
        "shacl_enabled": args.shacl,
        "shacl_retry_count": 0,
        "shacl_violation_fingerprint": "",
    }

    config = {"configurable": {"thread_id": str(uuid.uuid4())}}

    # ── Stage metadata for display ────────────────────────────────
    _STAGE_LABELS = {
        "analyze_schema":     "Schema Analysis",
        "scout_ontology":     "Ontology Scout",
        "map_semantics":      "Semantic Mapper",
        "generate_cqs":       "CQ Generator",
        "align_schema":       "Schema Alignment",
        "generate_yarrrml":   "YARRRML Generator",
        "validate_yarrrml":   "Syntax Validator",
        "refine_logic":       "Logic Refiner",
        "generate_kg":        "KG Generator",
        "shacl_validate":     "SHACL Validator",
        "sparql_validate_cqs":"SPARQL CQ Validator",
    }

    def _bar(char="=", width=62):
        return char * width

    print(f"\n  {'=' * 64}")
    print(f"  {'AGENTIC RML PIPELINE':^64}")
    print(f"  {'Run: ' + current_run_timestamp:^64}")
    print(f"  {'=' * 64}\n")

    # ── Execute pipeline with timing ─────────────────────────────
    t0 = time.time()
    stage_times: dict[str, float] = {}
    stage_start = time.time()

    for event in app.stream(initial_state, config):
        for node_name, output in event.items():
            elapsed_stage = time.time() - stage_start
            stage_times[node_name] = elapsed_stage
            label = _STAGE_LABELS.get(node_name, node_name)
            print(f"\n  +-- {label}  ({elapsed_stage:.1f}s) {'-' * max(2, 44 - len(label))}+")

            # ── Per-node detail ──────────────────────────────────
            if node_name == "analyze_schema":
                schema = output.get("schema_info", {})
                raw = schema.get("raw", {})
                cols = raw.get("columns", []) if isinstance(raw, dict) else []
                print(f"  |  Columns detected : {len(cols)}")
                if cols:
                    print(f"  |  {', '.join(str(c) for c in cols[:8])}{'...' if len(cols) > 8 else ''}")

            elif node_name == "scout_ontology":
                ont_raw = output.get("ontology_info", {}).get("raw", {})
                if isinstance(ont_raw, dict):
                    n_cls = len(ont_raw.get("classes", []))
                    n_op  = len(ont_raw.get("object_properties", []))
                    n_dp  = len(ont_raw.get("data_properties", []))
                    print(f"  |  Classes: {n_cls}  |  Object props: {n_op}  |  Data props: {n_dp}")
                else:
                    preview = str(ont_raw)[:80].replace("\n", " ")
                    print(f"  |  Ontology subgraph extracted: {preview}...")

            elif node_name == "generate_cqs":
                gen = output.get("generated_cqs", [])
                user = initial_state.get("competency_questions", [])
                if gen:
                    print(f"  |  Auto-generated {len(gen)} CQ(s)  (saved to cqs.txt)")
                elif user:
                    print(f"  |  Using {len(user)} user-provided CQ(s)  (saved to cqs.txt)")
                else:
                    print(f"  |  No CQs available -- SPARQL validation will be skipped")

            elif node_name == "align_schema":
                alignment = output.get("schema_alignment", {})
                alignment = alignment if isinstance(alignment, dict) else {}
                tag = "MULTI-NODE" if alignment.get("multi_node") else "FLAT"
                plan = alignment.get("entity_plan") or ""
                entities = [l for l in str(plan)[:120].split("\n") if l.strip()][:2]
                print(f"  |  Structure  : {tag}")
                for e in entities:
                    print(f"  |  {e.strip()[:60]}")

            elif node_name == "generate_yarrrml":
                retries = output.get("retry_count", 0)
                yarrrml = output.get("yarrrml_output", "")
                n_lines = len(yarrrml.splitlines())
                print(f"  |  Attempt #{retries}  |  YARRRML lines: {n_lines}")

            elif node_name == "validate_yarrrml":
                fb = output.get("feedback", "")
                if "PASSED" in fb:
                    print(f"  |  [PASS] YARRRML syntax is valid")
                else:
                    err = fb.replace("SYNTAX_ERROR:", "").strip()[:120]
                    print(f"  |  [FAIL] Syntax error -- will retry")
                    print(f"  |  {err}")

            elif node_name == "refine_logic":
                fb = output.get("feedback", "")
                if "APPROVED" in fb:
                    print(f"  |  [PASS] Logic check passed -- mapping approved")
                elif "LOGIC_ERROR" in fb:
                    lines = [l for l in fb.splitlines() if l.strip()][:5]
                    print(f"  |  [FAIL] Logic issues found -- will retry")
                    for l in lines:
                        print(f"  |    {l[:80]}")
                else:
                    print(f"  |  {fb[:100]}")

            elif node_name == "generate_kg":
                rdf = output.get("rdf_output", "")
                if rdf:
                    size = os.path.getsize(rdf) if os.path.exists(rdf) else 0
                    print(f"  |  [OK] KG materialised: {rdf}")
                    print(f"  |  File size: {size / 1024:.1f} KB")
                else:
                    print(f"  |  [FAIL] KG generation failed")

            elif node_name == "shacl_validate":
                fb = output.get("feedback", "")
                if "SHACL_PASSED" in fb:
                    print(f"  |  [PASS] KG conforms to all SHACL shapes")
                elif "SHACL_SKIP" in fb:
                    print(f"  |  [SKIP] SHACL validation not requested")
                elif "SHACL_ERROR" in fb:
                    lines = [l for l in fb.splitlines() if l.strip()][:5]
                    print(f"  |  [FAIL] SHACL violations detected -- routing back to generator")
                    for l in lines:
                        print(f"  |    {l[:80]}")

            elif node_name == "sparql_validate_cqs":
                fb = output.get("feedback", "")
                results = output.get("sparql_validation_results", [])
                n_total  = len(results)
                n_passed = sum(1 for r in results if r.get("passed") is True)
                n_failed = sum(1 for r in results if r.get("passed") is False)
                n_skip   = sum(1 for r in results if r.get("passed") is None)
                retry_n  = output.get("cq_sparql_retry_count", 0)
                if "CQ_SPARQL_PASSED" in fb:
                    print(f"  |  [PASS] All checks passed  ({n_passed}/{n_total})")
                elif "CQ_SPARQL_ERROR" in fb:
                    print(f"  |  [FAIL] {n_failed}/{n_total} check(s) failed  "
                          f"(retry {retry_n}) -- routing back to generator")
                    for r in results:
                        if r.get("passed") is False:
                            src = r.get("source", "?")
                            print(f"  |    FAIL [{src}] {r['cq'][:65]}")
                else:
                    print(f"  |  No CQs or SPARQL queries provided -- skipped")
                if n_skip:
                    print(f"  |  WARNING: {n_skip} check(s) had SPARQL generation issues -- skipped")

            # Always print the agent message if present
            if "messages" in output and output["messages"]:
                msg = output["messages"][-1]
                print(f"  |  -> {msg[:100]}")

            print(f"  +{'-' * 62}+")
            stage_start = time.time()

    elapsed = time.time() - t0
    result = app.get_state(config).values

    # ── Final Summary ─────────────────────────────────────────────
    print(f"\n  {'=' * 64}")
    print(f"  {'PIPELINE SUMMARY':^64}")
    print(f"  {'=' * 64}")

    rdf_path  = result.get("rdf_output", "")
    kg_ok     = bool(rdf_path and os.path.exists(rdf_path))
    retries   = result.get("retry_count", 0)
    sparql_results = result.get("sparql_validation_results", [])
    n_cq_pass = sum(1 for r in sparql_results if r.get("passed") is True)
    n_cq_fail = sum(1 for r in sparql_results if r.get("passed") is False)

    kg_status = "YES  --> " + rdf_path if kg_ok else "NO"
    print(f"  KG generated   : {kg_status}")
    print(f"  Total retries  : {retries}")
    print(f"  Total time     : {elapsed:.1f}s")
    if sparql_results:
        print(f"  CQ checks      : {n_cq_pass} passed / {n_cq_fail} failed")

    # Stage timing table
    print(f"\n  {'Stage':<38} {'Time':>8}  Progress")
    print(f"  {'-' * 62}")
    for sname, stime in stage_times.items():
        slabel = _STAGE_LABELS.get(sname, sname)
        bar_len = min(10, int(stime / max(elapsed, 1) * 10))
        tbar = "#" * bar_len + "." * (10 - bar_len)
        print(f"  {slabel:<38} {stime:>6.1f}s  [{tbar}]")
    print(f"  {'=' * 64}\n")

    # ── Output file summary ───────────────────────────────────────
    print(f"  Run directory: {run_directory}")

    yarrrml_content = result.get("yarrrml_output", "")
    if yarrrml_content:
        mapping_filename = os.path.join(run_directory, "final_mapping.yaml")
        with open(mapping_filename, "w") as f:
            f.write(yarrrml_content)
        print(f"  [saved] final_mapping.yaml  ({len(yarrrml_content.splitlines())} lines)")

    if kg_ok:
        sz = os.path.getsize(rdf_path) / 1024
        print(f"  [saved] knowledge_graph.nt  ({sz:.1f} KB)")

    cqs_file = os.path.join(run_directory, "cqs.txt")
    if os.path.exists(cqs_file):
        print(f"  [saved] cqs.txt")

    for fname in sorted(os.listdir(run_directory)):
        if fname.startswith("sparql_validation"):
            print(f"  [saved] {fname}")

    debug_dir = os.path.join(run_directory, "debug")
    if os.path.isdir(debug_dir):
        attempt_files = sorted(f for f in os.listdir(debug_dir) if f.startswith("attempt_"))
        if attempt_files:
            print(f"  [debug] debug/  ({len(attempt_files)} YARRRML attempt(s))")

    if not kg_ok:
        fb = result.get("feedback", "")
        print(f"\n  [FAIL] Pipeline did not produce a KG.  Last feedback:")
        for line in fb.split("\n")[:10]:
            if line.strip():
                print(f"         {line[:100]}")

    print()

    # ── Evaluation ───────────────────────────────────────────────
    eval_levels = args.eval_levels
    if eval_levels is not None:
        if not eval_levels:
            eval_levels = [1, 2, 3]
        eval_levels = sorted(set(eval_levels))
        invalid = [l for l in eval_levels if l not in (1, 2, 3)]
        if invalid:
            print(f"[WARN] Ignoring unknown eval levels: {invalid}")
            eval_levels = [l for l in eval_levels if l in (1, 2, 3)]

        if eval_levels:
            from evaluation.metrics import evaluate, print_metrics
            from config.settings import get_llm_metadata
            import json

            gold_path = args.gold
            if gold_path is None and 2 in eval_levels:
                default_gold = "data/gold/bikeshare_gold.nt"
                if os.path.isfile(default_gold):
                    gold_path = default_gold
                else:
                    print("[WARN] No --gold path provided and data/gold/bikeshare_gold.nt not found.")
                    print("   Level 2 evaluation will be skipped.")

            if "csv_path" not in result:
                result["csv_path"] = os.getenv("INPUT_CSV_PATH")

            metrics = evaluate(
                levels=eval_levels,
                pipeline_result=result,
                gold_kg_path=gold_path,
                elapsed_time=elapsed,
            )
            metrics.update(get_llm_metadata())
            print_metrics(metrics, eval_levels)

            metrics_file = os.path.join(run_directory, "eval_metrics.json")
            with open(metrics_file, "w") as f:
                json.dump(metrics, f, indent=2, default=str)
            print(f"\n  Evaluation metrics saved to: {metrics_file}")

    # ── Dashboard ────────────────────────────────────────────────
    if args.dashboard is not None:
        from tools.dashboard import main as dashboard_main
        print(f"\nLaunching metrics dashboard (last {args.dashboard} runs)...")
        sys.argv = [
            "dashboard",
            "--runs", str(args.dashboard),
            "--output-dir", "data/output",
        ]
        dashboard_main()


if __name__ == "__main__":
    main()





